let assign = 15;
console.log(assign);
assign += 10;
console.log(assign);
assign -= 10;
console.log(assign);
assign /= 10;
console.log(assign);
assign = 15;
assign %= 10;
console.log(assign);
assign *= 5;
console.log(assign);
assign = 5;
assign **= 3;
console.log(assign);
